### ISSUE TITLE
PA Review: Lodgings

### ISSUE THREAD

**Issue by ckim2013** [ckim2013/skybnb#10]

**Comment by debsfong** [comment]
Looks great! There are a couple small, non-intuitive things, but they're lower priority than getting the rest of your MVPs done. 
- [ ] after uploading a picture, I thought that I was able to add multiple pictures. Turns out that it just replaces the old one
- [ ] the check in time should be some type of time picker. Maybe just a drop down with half hour increments? And maybe should be a range (e.g. check in from 3 - 5pm)
Other than that, it's done!
