### ISSUE TITLE
PA Review: Bookings

### ISSUE THREAD

**Issue by ckim2013** [ckim2013/skybnb#15]

**Comment by debsfong** [comment]
- [ ] Rather than the text "Denied", maybe put "Sign in to book!" and link to sign in
- [ ] Do not allow bookings in the past
- [ ] Add functionality to only book on available dates
- [ ] Remove lorem ipsum (Not urgent. Just not good to have it)
- [ ] I would also like to see a "My Places" section on the Bookings page, just so that I can get to them easily and delete them (Also not necessary, but would be nice to have)

**Comment by debsfong** [comment]
Looks good!
